#pragma once

#if MC_VERSION == v1_21_2
enum class BlockRenderLayer : uint64_t {
#elif MC_VERSION == v1_21_50 || MC_VERSION == v1_21_60
enum class BlockRenderLayer : uint8_t {
#endif
    RENDERLAYER_DOUBLE_SIDED = 0,
    RENDERLAYER_RAYTRACED_WATER = 1,
    RENDERLAYER_DEFERRED_WATER = 2,
    RENDERLAYER_BLEND = 3,
    RENDERLAYER_OPAQUE = 4,
    RENDERLAYER_LIGHT_SOURCE = 5,
    RENDERLAYER_OPTIONAL_ALPHATEST = 6,
    RENDERLAYER_ALPHATEST = 7,
    RENDERLAYER_SEASONS_OPAQUE = 8,
    RENDERLAYER_SEASONS_OPTIONAL_ALPHATEST = 9,
    RENDERLAYER_ALPHATEST_SINGLE_SIDE = 10,
    RENDERLAYER_ENDPORTAL = 11,
    RENDERLAYER_BARRIER = 12,
    RENDERLAYER_LIGHT = 13,
    RENDERLAYER_STRUCTURE_VOID = 14,
    _RENDERLAYER_COUNT = 15,
};
