#pragma once

enum class ContainerID : signed char {
    CONTAINER_ID_NONE = -1,
    CONTAINER_ID_INVENTORY = 0,
    CONTAINER_ID_FIRST = 1,
    CONTAINER_ID_LAST = 100,
    CONTAINER_ID_OFFHAND = 119,
    CONTAINER_ID_ARMOR = 120,
    CONTAINER_ID_CREATIVE = 121,
    CONTAINER_ID_SELECTION_SLOTS = 122,
    CONTAINER_ID_PLAYER_ONLY_UI = 124,
    CONTAINER_ID_REGISTRY = 125,
};