#pragma once

enum class ActorCategory : uint32_t {
    None = 0,
    Player = 1,
    Mob = 1 << 1,
    Monster = 1 << 2,
    Humandoid = 1 << 3,
    HumanoidMonster = Humandoid | Monster,
    Animal = 1 << 4,
    WaterSpawning = 1 << 5,
    WaterAnimal = WaterSpawning | Animal,
    Pathable = 1 << 6,
    Tamable = 1 << 7,
    TamableAnimal = Tamable | Animal,
    Ridable = 1 << 8,
    Item = 1 << 10,
    Ambient = 1 << 11,
    Villager = 1 << 12,
    EvocationIllagerMonster = Villager | HumanoidMonster,
    Arthropod = 1 << 13,
    Undead = 1 << 14,
    UndeadMob = Undead | Mob,
    Zombie = 1 << 15,
    ZombieMonster = Zombie | Monster,
    Minecart = 1 << 16,
    MinecartRidable = Minecart | Ridable,
    Boat = 1 << 17,
    BoatRideable = Boat | Ridable,
    NonTargetable = 1 << 18,
    Predictable = 1u << 19,
};