name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Setup Windows 10 SDK Action
      uses: GuillaumeFalourd/setup-windows10-sdk-action@v2.4
      with:
        sdk-version: 22621

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_SYSTEM_VERSION="10.0.22621.0"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Install
      run: cmake --install build --config ${{env.BUILD_TYPE}}

    - name: Package
      run: cmake --build build --target package --config ${{env.BUILD_TYPE}}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sapphire-windows-build-${{github.sha}}
        path: ${{github.workspace}}/build/Sapphire-*.*.*-win64-*.zip
